### ISSUE TITLE
点击下载显示加载图片出错:
java.lang.NullPointerException
加载视频详情出错:
java.lang.NullPointerException

### ISSUE THREAD

**Issue by wanxiang751** [HydeYYHH/YouTube-lite#2]

**Comment by HydeYYHH** [comment]
你是所有视频都报这个错，还是个别视频

**Comment by wanxiang751** [comment]
> 你是所有视频都报这个错，还是个别视频
所有视频都是报错

**Comment by HydeYYHH** [comment]
> > 你是所有视频都报这个错，还是个别视频
> > 所有视频都是报错

出现这个报错的原因一般是因为解析视频返回了错误的响应, 可以参考 https://github.com/sealedtx/java-youtube-downloader#:~:text=At%20present%20because,one%20for%20playlists. 和 https://github.com/sealedtx/java-youtube-downloader/issues/130 . 我这里只出现过部分视频报这个错, 比如 https://youtu.be/UBkUt7KpJRk?si=IgqeHWrGcqBHObLp 这个, 你能具体发一两个报错的视频吗

**Comment by HydeYYHH** [comment]
@wanxiang751 你试试这个版本看好了没 https://github.com/HydeYYHH/YouTube-lite/releases/tag/v1.4.8-pre

**Comment by HydeYYHH** [comment]
如果在国内的话，建议换一下结点，好像跟这个有关系

**Comment by wanxiang751** [comment]
> 如果在国内的话，建议换一下结点，好像跟这个有关系
换了其他代理就没问题了
